### ISSUE TITLE
Fix OffsetOutOfRange error automatically if possible

### ISSUE THREAD

**Issue by rinzeb** [DRIVER-EU/node-test-bed-adapter#5]
When trying to consume a topic from an offset, say 200, while the latest offset is only at 50, this will result in a OffsetOutOfRange error. It can be prevented by fetching the latest offset and use that as a cap before subscribing to a topic.

**Comment by rinzeb** [comment]
[node-test-bed-adapter-0.4.6.tar.gz](https://github.com/DRIVER-EU/node-test-bed-adapter/files/2333008/node-test-bed-adapter-0.4.6.tar.gz)

**Comment by erikvullings** [comment]
Integrated code changes in latest version
